services:
  database:
    image: mysql:8.0
    container_name: gerenciamento_consultas
    restart: always
    environment:
      MYSQL_DATABASE: gerenciamento_consultas
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
